---
title: "Chloro"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(here)
library(tidyverse)
library(janitor)
library(ggExtra)

```

```{r}
raw_chloro <- read_csv(here("/Users", "eisaguirre", "github", "SST", "data", "Chloro.csv"))

```

```{r}

chloro <- raw_chloro[-c(2)] 
  
clean_chloro <- chloro[-c(1),] 

mut_chloro <- clean_chloro %>% 
  mutate(data.frame(longitude = as.numeric(clean_chloro$longitude))) %>% 
  mutate(data.frame(latitude = as.numeric(clean_chloro$latitude))) %>% 
  mutate(data.frame(chlorophyll = as.numeric(clean_chloro$chlorophyll)))

```

```{r}

ggplot(mut_chloro, aes(y=latitude, x=longitude)) +
  geom_raster(aes(fill = chlorophyll), 
              show.legend = T, 
              interpolate = T, 
              hjust = 1, 
              vjust = 1) +
  scale_fill_viridis_c(option = "turbo") +
  theme_light() +
  labs(x = "Longitude",
       y = "Latitude",
       color = "",
       fill = "Chlorophyll 
(mg m^-3)") +
  theme(panel.grid = element_line(F)) +
  scale_x_continuous(breaks = c(-120.5, -120, -119.5, -119))

```

